import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const navigation = [
  { name: 'Home', href: '/' },
  { name: 'Challanges', href: '/challanges' },
  { name: 'Speakers', href: '/speakers' },
  { name: 'Workshops', href: '/workshops' },
  { name: 'Schedule', href: '/schedule' },
  { name: 'Venue', href: '/venue' },
];

export const metadata: Metadata = {
  title: "IEEE SIGHT DAY CONGRESS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar  navigation={navigation} />
        
        {children}
      </body>
    </html>
  );
}
